# syntax=dhi.io/build:2-helm3

name: Velero Helm chart 11.x
image: dhi.io/velero-chart
variant: helm
tags:
  - 11.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13-compat@sha256:467e61e08f65762a757847e281c8c5d79330b90d92a73c895dac9c3c807c5499
  SEMVER_MAJOR_MINOR_VERSION: "11.3"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.3.2
  VELERO_REFERENCE: dhi/velero:1.18.0-debian13@sha256:e84c9455386f7a526a6205d6f493b95587fba4aef63dc8355008819ed502f0be
  VERSION: 11.3.2
contents:
  builds:
    - name: velero
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/vmware-tanzu/helm-charts.git#velero-11.3.2
            checksum: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            chart:
              appRef: velero
              description: Docker Hardened Images Helm chart for Velero
              images:
                - name: velero
                  ref: dhi/velero:1.18.0-debian13@sha256:e84c9455386f7a526a6205d6f493b95587fba4aef63dc8355008819ed502f0be
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13-compat@sha256:467e61e08f65762a757847e281c8c5d79330b90d92a73c895dac9c3c807c5499
              name: velero-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vmware-tanzu/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: velero
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/velero/config
