metadata:
  display-name: Tailscale Operator Helm chart
  short-description: A hardened Helm chart for the Tailscale Kubernetes Operator.
  featured: false
  home-url: https://tailscale.com
  categories:
    - networking
    - security
