# syntax=dhi.io/build:2-helm3

name: Prometheus Adapter Helm chart 5.x
image: dhi.io/prometheus-adapter-chart
variant: helm
tags:
  - 5.3.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: e6e041b675fc44c3b869dfbb88d183e40b449dd2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  PROMETHEUS_ADAPTER_REFERENCE: dhi/prometheus-adapter:0.12.0-debian13@sha256:f991b8be7aa3f748185b5a2d839a860da5e9d74b704781be18ed012ebcb08f8b
  SEMVER_MAJOR_MINOR_VERSION: "5.3"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.3.0
  VERSION: 5.3.0
contents:
  builds:
    - name: prometheus-adapter-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-adapter-5.3.0
            checksum: e6e041b675fc44c3b869dfbb88d183e40b449dd2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-adapter
          with:
            chart:
              appRef: prometheus-adapter
              description: Docker Hardened Images Helm chart for Prometheus Adapter
              images:
                - name: prometheus-adapter
                  ref: dhi/prometheus-adapter:0.12.0-debian13@sha256:f991b8be7aa3f748185b5a2d839a860da5e9d74b704781be18ed012ebcb08f8b
              name: prometheus-adapter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-adapter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-adapter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/prometheus-adapter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus-adapter/config
