# syntax=dhi.io/build:2-helm3

name: Prometheus Blackbox Exporter Helm chart 11.x
image: dhi.io/blackbox-exporter-chart
variant: helm
tags:
  - 11.10.0
platforms:
  - linux/amd64
vars:
  BLACKBOX_EXPORTER_REFERENCE: dhi/blackbox-exporter:0.28.0-debian13@sha256:7ff4fb470707695be49b2d17f3dc6130c0558200657b6f9334e3e6217e0ffb0f
  CHART_COMMIT_SHA: 9d11947585b0a01c9220dea0e08d505c5c87c395
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:663521947cad99f56d0550697a339d39296e4475bf769aa8fb1c7c220ab713fd
  SEMVER_MAJOR_MINOR_VERSION: "11.10"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.10.0
  VERSION: 11.10.0
contents:
  builds:
    - name: blackbox-exporter-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-blackbox-exporter-11.10.0
            checksum: 9d11947585b0a01c9220dea0e08d505c5c87c395
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            chart:
              appRef: blackbox-exporter
              description: Docker Hardened Images Helm chart for Prometheus Blackbox Exporter
              images:
                - name: blackbox-exporter
                  ref: dhi/blackbox-exporter:0.28.0-debian13@sha256:7ff4fb470707695be49b2d17f3dc6130c0558200657b6f9334e3e6217e0ffb0f
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:663521947cad99f56d0550697a339d39296e4475bf769aa8fb1c7c220ab713fd
              name: blackbox-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-blackbox-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/blackbox-exporter/config
