# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 13.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 13.7.2
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.3.12-debian13@sha256:a69172f158606588e570736927e686c5902e971f76c4dc4570f0209cc304ca3a
  CHART_COMMIT_SHA: 318302c04398971a6ebae358a4d5b2a388f1ce58
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:1448615514d4e238504996d41ae9a4a09ae288427c457ac5ed5a12446fb444bf
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:b45ef2bf135ceb84156067843fefb8b06db1974e2a5304e994149b8c812c9685
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.1-debian13@sha256:149ad6f12cf2f67f7d7cb75ff1fc990c880424cc40ba0e7a493572ba6ec95e6d
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.2-debian13@sha256:07f9d0fd3b87f5867e92af66d929533a9a07a6dc5744a91b3369558d2ae68562
  LOKI_REFERENCE: dhi/loki:3.7.1-debian13@sha256:3f57b881f1eff317bea1b122db1eceb4d4b34fc38d9272d69ad3b82b92431512
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:567b9810400d99c613fdf31117a7e8c4240cf4f29f9607e90bd6f522d765d4fd
  MEMCACHED_REFERENCE: dhi/memcached:1.6.42-debian13@sha256:d0ddf23ece0ef4be9e1026bc4f12a1f6e0726cbceeb9ae3119f2d2f1e073d441
  NGINX_REFERENCE: dhi/nginx:1.31.0-debian13@sha256:07477e2829f4f800abcdf369a93c9e5ec5dc4b17b2b86deb44063414aec3cd16
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.49.0@sha256:c391ffbd757ba3ddbadcbab9415832b61aea33b8131a67fc0d27fe887728a045
  SEMVER_MAJOR_MINOR_VERSION: "13.7"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.7.2
  VERSION: 13.7.2
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-13.7.2
            checksum: 318302c04398971a6ebae358a4d5b2a388f1ce58
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.49.0@sha256:c391ffbd757ba3ddbadcbab9415832b61aea33b8131a67fc0d27fe887728a045
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.1-debian13@sha256:3f57b881f1eff317bea1b122db1eceb4d4b34fc38d9272d69ad3b82b92431512
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.1-debian13@sha256:149ad6f12cf2f67f7d7cb75ff1fc990c880424cc40ba0e7a493572ba6ec95e6d
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.2-debian13@sha256:07f9d0fd3b87f5867e92af66d929533a9a07a6dc5744a91b3369558d2ae68562
                - name: nginx
                  ref: dhi/nginx:1.31.0-debian13@sha256:07477e2829f4f800abcdf369a93c9e5ec5dc4b17b2b86deb44063414aec3cd16
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:1448615514d4e238504996d41ae9a4a09ae288427c457ac5ed5a12446fb444bf
                - name: memcached
                  ref: dhi/memcached:1.6.42-debian13@sha256:d0ddf23ece0ef4be9e1026bc4f12a1f6e0726cbceeb9ae3119f2d2f1e073d441
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:567b9810400d99c613fdf31117a7e8c4240cf4f29f9607e90bd6f522d765d4fd
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.3.12-debian13@sha256:a69172f158606588e570736927e686c5902e971f76c4dc4570f0209cc304ca3a
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:b45ef2bf135ceb84156067843fefb8b06db1974e2a5304e994149b8c812c9685
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
