# syntax=dhi.io/build:2-helm3

name: Opencost Helm chart 2.x
image: dhi.io/opencost-chart
variant: helm
tags:
  - 2.5.20
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.120.2
  AWS_SIGV4_PROXY_IMAGE_REFERENCE: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:120b310d4fb232750c7c48fcb5efcc984ec16866e2f81b6cba8741cde670a682
  CHART_COMMIT_SHA: fc561629b7e4123636f9e11dbe50735f6052b5b5
  CURL_IMAGE_REFERENCE: dhi/curl:8.14.1-debian13@sha256:35690d5c1c8840d2f85a599a31645cd0ee81d09173d264245b3d9c6b54086503
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  OPENCOST_IMAGE_REFERENCE: dhi/opencost:1.120.2-debian13@sha256:9eaec320b347dbdca326e37137e7aff7d79af5dd6ed401b738879ecff1144a1c
  OPENCOST_UI_IMAGE_REFERENCE: dhi/opencost-ui:1.120.2-debian13@sha256:2c59d25cde87d12e5aeac22ee1d4300d9a9cf3fd0bc9df2716e69d8026356191
  SEMVER_MAJOR_MINOR_VERSION: "2.5"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.5.20
  VERSION: 2.5.20
contents:
  builds:
    - name: opencost-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      work-dir: ${source.dir}/helm-charts/charts/opencost
      contents:
        files:
          - url: git+https://github.com/opencost/opencost-helm-chart.git#opencost-2.5.20
            checksum: fc561629b7e4123636f9e11dbe50735f6052b5b5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opencost
          with:
            chart:
              appRef: opencost
              description: Docker Hardened Images Helm chart for Opencost
              images:
                - name: opencost
                  ref: dhi/opencost:1.120.2-debian13@sha256:9eaec320b347dbdca326e37137e7aff7d79af5dd6ed401b738879ecff1144a1c
                - name: opencost-ui
                  ref: dhi/opencost-ui:1.120.2-debian13@sha256:2c59d25cde87d12e5aeac22ee1d4300d9a9cf3fd0bc9df2716e69d8026356191
                - name: aws-sigv4-proxy
                  ref: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:120b310d4fb232750c7c48fcb5efcc984ec16866e2f81b6cba8741cde670a682
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:35690d5c1c8840d2f85a599a31645cd0ee81d09173d264245b3d9c6b54086503
              name: opencost-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/opencost/opencost
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opencost/config
