# syntax=dhi.io/build:2-helm3

name: OAuth2 Proxy Helm chart 10.x
image: dhi.io/oauth2-proxy-chart
variant: helm
tags:
  - 10.4.3
platforms:
  - linux/amd64
vars:
  ALPINE_BASE_REFERENCE: dhi/alpine-base:3.22-alpine3.22@sha256:e46de8d59c111eb1455c81e2e3deea7437a7d7e26e340ad8c756878f519f5f13
  CHART_COMMIT_SHA: b2987f8ba9969b93ef0da84e224ad3683fad473d
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  OAUTH2_PROXY_REFERENCE: dhi/oauth2-proxy:7.15.2-debian13@sha256:1007c446ac10fbbb67df2905fb611010a538e5343922509c03400c478b83850a
  REDIS_CHART_REFERENCE: dhi/redis-chart:23.0.7@sha256:474638eff144f2af48acd7e00b95ae41ce8f3f5223303426828584697346c9ca
  SEMVER_MAJOR_MINOR_VERSION: "10.4"
  SEMVER_MAJOR_VERSION: "10"
  SEMVER_VERSION: 10.4.3
  VERSION: 10.4.3
contents:
  builds:
    - name: oauth2-proxy
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/oauth2-proxy/manifests.git#oauth2-proxy-10.4.3
            checksum: b2987f8ba9969b93ef0da84e224ad3683fad473d
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy
          with:
            chart:
              appRef: oauth2-proxy
              dependencies:
                - alias: redis
                  condition: redis-ha.enabled
                  name: redis-chart
                  ref: dhi/redis-chart:23.0.7@sha256:474638eff144f2af48acd7e00b95ae41ce8f3f5223303426828584697346c9ca
              description: Docker Hardened Images Helm chart for OAuth2 Proxy
              images:
                - name: oauth2-proxy
                  ref: dhi/oauth2-proxy:7.15.2-debian13@sha256:1007c446ac10fbbb67df2905fb611010a538e5343922509c03400c478b83850a
                - name: alpine-base
                  ref: dhi/alpine-base:3.22-alpine3.22@sha256:e46de8d59c111eb1455c81e2e3deea7437a7d7e26e340ad8c756878f519f5f13
              name: oauth2-proxy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/oauth2-proxy/manifests
            cmd: prepare
            registry: dhi.io
        - name: patch helpers
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy/templates
          runs: |
            set -eux -o pipefail

            sed -i 's/include "redis-ha.fullname"/include "common.names.fullname"/' _helpers.tpl
            sed -i 's/(dict "Chart" (dict "Name" "redis-ha")/(dict "Chart" (dict "Name" "redis")/' _helpers.tpl
            sed -i 's|printf "redis://%s:%.0f"|printf "redis://%s-master:%.0f"|' _helpers.tpl
            sed -i 's/$redisValues.redis.port/.Values.redis.master.service.ports.redis/' _helpers.tpl
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/helm/oauth2-proxy
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm
          with:
            chart: oauth2-proxy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/helm/oauth2-proxy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/oauth2-proxy/config
