# syntax=dhi.io/build:2-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.55.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 0371ce7dac3c16698547a72370324f4b9432e0ea
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.22.0-debian13@sha256:8478efda0d25ac2b4c73d4741cd479a7000909dd7391a5446ff739c5f87014ad
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.11.1-debian13@sha256:bf6ec8487378b015ac19f79e51f1e197a036db15953144ee158c25687e6a81a2
  SEMVER_MAJOR_MINOR_VERSION: "4.55"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.55.0
  VERSION: 4.55.0
contents:
  builds:
    - name: node-exporter-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.55.0
            checksum: 0371ce7dac3c16698547a72370324f4b9432e0ea
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.11.1-debian13@sha256:bf6ec8487378b015ac19f79e51f1e197a036db15953144ee158c25687e6a81a2
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.22.0-debian13@sha256:8478efda0d25ac2b4c73d4741cd479a7000909dd7391a5446ff739c5f87014ad
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
