# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.7.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.7.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.17.2
  CHART_COMMIT_SHA: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  KUBECTL_IMAGE_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:192c542342d8df9418e17303d59a976fa18b3b79b2b6680c1885c912b2ca5417
  KYVERNO_BACKGROUND_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-background-controller:1.17.2-debian13@sha256:f92d2f7bb975ed47ba2f6de25122546c7517fb0eccd4d43b9f337445fb760874
  KYVERNO_CLEANUP_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:7967a48e8b420386a053f98460eacb43ab14bab809f6dc3056c7bb04beffa405
  KYVERNO_CLI_IMAGE_REFERENCE: dhi/kyverno-cli:1.17.2-debian13@sha256:ff13afa7eebbb50668008ba554845640daeea3031d99544900a4951ca9ab4b14
  KYVERNO_IMAGE_REFERENCE: dhi/kyverno:1.17.2-debian13@sha256:eb93e43503b06ae7680e81b5f860e931ed85ec17ab347fb0db25066f150983d1
  KYVERNO_INIT_IMAGE_REFERENCE: dhi/kyverno-init:1.17.2-debian13@sha256:53b49aba3890ca92e0f83dd9bc4e066efb2afe6572ced2e2bf4daea21369ed1a
  KYVERNO_READINESS_CHECKER_IMAGE_REFERENCE: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:ffada62e8e9d283cc8e80fe0316a69a381dcd0363d21280e04e191b3f1da67c1
  KYVERNO_REPORTS_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:c9e763abccc04a0b75d6526eb9558135807dd871a1158391ed1df471ca80df18
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:0a4e42b9202bf5ca43f7cc01fc05a466d9a341e1ebcfa23dd3c757fcd8653afa
  SEMVER_MAJOR_MINOR_VERSION: "3.7"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.7.2
  VERSION: 3.7.2
contents:
  builds:
    - name: kyverno-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.7.2
            checksum: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:0a4e42b9202bf5ca43f7cc01fc05a466d9a341e1ebcfa23dd3c757fcd8653afa
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.17.2-debian13@sha256:eb93e43503b06ae7680e81b5f860e931ed85ec17ab347fb0db25066f150983d1
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.17.2-debian13@sha256:ff13afa7eebbb50668008ba554845640daeea3031d99544900a4951ca9ab4b14
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:ffada62e8e9d283cc8e80fe0316a69a381dcd0363d21280e04e191b3f1da67c1
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:192c542342d8df9418e17303d59a976fa18b3b79b2b6680c1885c912b2ca5417
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.17.2-debian13@sha256:53b49aba3890ca92e0f83dd9bc4e066efb2afe6572ced2e2bf4daea21369ed1a
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.17.2-debian13@sha256:f92d2f7bb975ed47ba2f6de25122546c7517fb0eccd4d43b9f337445fb760874
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:7967a48e8b420386a053f98460eacb43ab14bab809f6dc3056c7bb04beffa405
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:c9e763abccc04a0b75d6526eb9558135807dd871a1158391ed1df471ca80df18
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
