# syntax=dhi.io/build:2-helm3

name: Kyverno Reports Server Helm chart 0.x
image: dhi.io/kyverno-reports-server-chart
variant: helm
tags:
  - 0.1.7
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: d2b451bf72c175f25a653265a03002de7c0e0d3c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  KUBECTL_IMAGE_REFERENCE: dhi/kubectl:1.35.5-debian13-compat@sha256:467e61e08f65762a757847e281c8c5d79330b90d92a73c895dac9c3c807c5499
  KYVERNO_REPORTS_SERVER_IMAGE_REFERENCE: dhi/kyverno-reports-server:0.1.7-debian13@sha256:6c8496c2989ee63cc4e7c4f386d3e3bba0b3c598234434bb640ae33ad37a2adb
  SEMVER_MAJOR_MINOR_VERSION: "0.1"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.1.7
  VERSION: 0.1.7
contents:
  builds:
    - name: kyverno-reports-server-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/kyverno/reports-server.git#reports-server-chart-0.1.7
            checksum: d2b451bf72c175f25a653265a03002de7c0e0d3c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/reports-server
          with:
            chart:
              appRef: kyverno-reports-server
              dependencies: null
              description: Docker Hardened Images Helm chart for Kyverno Reports Server
              images:
                - name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server:0.1.7-debian13@sha256:6c8496c2989ee63cc4e7c4f386d3e3bba0b3c598234434bb640ae33ad37a2adb
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13-compat@sha256:467e61e08f65762a757847e281c8c5d79330b90d92a73c895dac9c3c807c5499
              name: kyverno-reports-server-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/reports-server
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/reports-server
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update chart dependencies
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/reports-server
          with:
            file: Chart.yaml
            patches:
              - del(.dependencies[] | select(.name == "postgresql"))
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/reports-server
          with:
            file: values.yaml
            patches:
              - del(.postgresql)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: reports-server
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: reports-server
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: reports-server
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno-reports-server/config
