# syntax=dhi.io/build:2-helm3

name: Istio Ingress Helm chart 1.x
image: dhi.io/istio-ingress-chart
variant: helm
tags:
  - 1.29.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 0c774325b938c4dbda4ea4ad4fb6156e80a12de8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.29.2-debian13@sha256:c48e8c0f0ecf80b8c25ed3237cd3e937460b7d9ae30d921f4760e6e5e2a587bb
  SEMVER_MAJOR_MINOR_VERSION: "1.29"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.29.2
  VERSION: 1.29.2
contents:
  builds:
    - name: istio-ingress
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      work-dir: ${source.dir}/helm-charts/manifests/charts/gateways/istio-ingress
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.29.2
            checksum: 0c774325b938c4dbda4ea4ad4fb6156e80a12de8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: proxyv2
              description: Docker Hardened Images Helm chart for Istio Ingress
              images:
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.29.2-debian13@sha256:c48e8c0f0ecf80b8c25ed3237cd3e937460b7d9ae30d921f4760e6e5e2a587bb
              name: istio-ingress-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-ingress/config
