# syntax=dhi.io/build:2-helm3

name: Redis Helm chart 23.x
image: dhi.io/redis-chart
variant: helm
tags:
  - 23.0.7
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:bd10790285ddd97bcbf296a955ec9c46161f0ed66da0d3bf2b749233a0ab6ddb
  CHART_COMMIT_SHA: 4f7288e1b226ee2bfc150e507ffdca04a98a0952
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  KUBECTL_REFERENCE: dhi/kubectl:1.34.8-debian13-compat@sha256:2b6d6fd2bfe56e27cba95ef91b167b8bb6f65b5fc4f6b9dc80f08a132281329a
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.83.0-debian13-compat@sha256:c3a73cd3f9a806984f085b810df2199c65d41d2780e106e18b282434c48a08bd
  REDIS_REFERENCE: dhi/redis:8.2.6-debian13-compat@sha256:43805a1ab4afacf8ff31e78b8c5d4d85f222be5e4f80d592dcb024d7427cef6e
  SEMVER_MAJOR_MINOR_VERSION: "23.0"
  SEMVER_MAJOR_VERSION: "23"
  SEMVER_VERSION: 23.0.7
  VERSION: 23.0.7
contents:
  builds:
    - name: redis
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      contents:
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#redis/23.0.7
            checksum: 4f7288e1b226ee2bfc150e507ffdca04a98a0952
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            chart:
              appRef: redis
              description: Docker Hardened Images Helm chart for Redis
              images:
                - name: redis
                  ref: dhi/redis:8.2.6-debian13-compat@sha256:43805a1ab4afacf8ff31e78b8c5d4d85f222be5e4f80d592dcb024d7427cef6e
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.83.0-debian13-compat@sha256:c3a73cd3f9a806984f085b810df2199c65d41d2780e106e18b282434c48a08bd
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:bd10790285ddd97bcbf296a955ec9c46161f0ed66da0d3bf2b749233a0ab6ddb
                - name: kubectl
                  ref: dhi/kubectl:1.34.8-debian13-compat@sha256:2b6d6fd2bfe56e27cba95ef91b167b8bb6f65b5fc4f6b9dc80f08a132281329a
              name: redis-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/redis
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: redis
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/redis
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/redis/config
