# syntax=dhi.io/build:2-helm3

name: Grafana k6-operator Helm chart 4.x
image: dhi.io/k6-operator-chart
variant: helm
tags:
  - 4.4.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 2ec227335b3e91a255d4253bd8da83e5da66966b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  K6_OPERATOR_REFERENCE: dhi/k6-operator:1.4.0-debian13@sha256:84d26d6b108c3782629f778dc4071a1dda3e0cfe1ea67d610a028aff449fe701
  K6_REFERENCE: dhi/k6:1.7.1-debian13-compat@sha256:61159f5bffbc431a07107f6554db68c37db6f5fa8af18578cf4aefd6e6583ff4
  SEMVER_MAJOR_MINOR_VERSION: "4.4"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.4.1
  VERSION: 4.4.1
contents:
  builds:
    - name: k6-operator
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      work-dir: /src/go/github.com/grafana/k6-operator/charts/k6-operator
      contents:
        files:
          - url: git+https://github.com/grafana/k6-operator.git#helm-k6-operator-4.4.1
            checksum: 2ec227335b3e91a255d4253bd8da83e5da66966b
            path: /src/go/github.com/grafana/k6-operator
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: k6-operator
              description: Docker Hardened Images Helm chart for Grafana k6 Kubernetes operator
              images:
                - name: k6-operator
                  ref: dhi/k6-operator:1.4.0-debian13@sha256:84d26d6b108c3782629f778dc4071a1dda3e0cfe1ea67d610a028aff449fe701
                - name: k6
                  ref: dhi/k6:1.7.1-debian13-compat@sha256:61159f5bffbc431a07107f6554db68c37db6f5fa8af18578cf4aefd6e6583ff4
              name: k6-operator
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/k6-operator
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/k6-operator/config
