# syntax=dhi.io/build:2-helm3

name: APISIX Ingress Controller Helm chart 1.x
image: dhi.io/apisix-ingress-controller-chart
variant: helm
tags:
  - 1.1.2
platforms:
  - linux/amd64
vars:
  ADC_IMAGE_REFERENCE: dhi/adc:0.25.0-debian13@sha256:0fdb570fba49eb826df14d2deafd0a70f95020f83d19358b5bbdc5017a22befb
  APISIX_INGRESS_CONTROLLER_IMAGE_REFERENCE: dhi/apisix-ingress-controller:2.0.1-debian13@sha256:2c72ab7b9c5a5abc576105c6f3a0dda19eb0ef6669ae1fba00ec45b178b13479
  CHART_COMMIT_SHA: 737c1639924ed705e6b561df0ac258683f7d323b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  SEMVER_MAJOR_MINOR_VERSION: "1.1"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.1.2
  VERSION: 1.1.2
contents:
  builds:
    - name: apisix-ingress-controller-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      contents:
        files:
          - url: git+https://github.com/apache/apisix-helm-chart.git#apisix-ingress-controller-1.1.2
            checksum: 737c1639924ed705e6b561df0ac258683f7d323b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          with:
            chart:
              appRef: apisix-ingress-controller
              description: Docker Hardened Images Helm chart for APISIX Ingress Controller
              images:
                - name: apisix-ingress-controller
                  ref: dhi/apisix-ingress-controller:2.0.1-debian13@sha256:2c72ab7b9c5a5abc576105c6f3a0dda19eb0ef6669ae1fba00ec45b178b13479
                - name: adc
                  ref: dhi/adc:0.25.0-debian13@sha256:0fdb570fba49eb826df14d2deafd0a70f95020f83d19358b5bbdc5017a22befb
              name: apisix-ingress-controller-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/apache/apisix-ingress-controller
            cmd: prepare
            registry: dhi.io
        - name: add image pull secrets
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          runs: |
            set -eux -o pipefail

            sed -i '/^      containers:/i\
                  {{- with .Values.imagePullSecrets }}\
                  imagePullSecrets:\
                    {{- range $.Values.imagePullSecrets }}\
                    - name: {{ . }}\
                    {{- end }}\
                  {{- end }}' templates/deployment.yaml
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix-ingress-controller
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix-ingress-controller
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/apisix-ingress-controller/config
