# syntax=dhi.io/build:2-helm3

name: Vector Helm chart 0.x
image: dhi.io/vector-chart
variant: helm
tags:
  - 0.52.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 6ce36995480f6dcafd81c162e4377f5e0a6035eb
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_REFERENCE: dhi/haproxy:3.0.23-debian13@sha256:0c6831cc8dcefce628f14fb0edbd3e59f3c3ecb32f14f49000bb40dd35a00f2f
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  SEMVER_MAJOR_MINOR_VERSION: "0.52"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.52.0
  VECTOR_REFERENCE: dhi/vector:0.55.0-debian13@sha256:6b102e2d9c1707adf6201d8ef361f993a2ceadd7393108b7bd69654a55cc9c52
  VERSION: 0.52.0
contents:
  builds:
    - name: vector-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/vectordotdev/helm-charts.git#vector-0.52.0
            checksum: 6ce36995480f6dcafd81c162e4377f5e0a6035eb
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            chart:
              appRef: vector
              description: Docker Hardened Images Helm chart for Vector
              images:
                - name: vector
                  ref: dhi/vector:0.55.0-debian13@sha256:6b102e2d9c1707adf6201d8ef361f993a2ceadd7393108b7bd69654a55cc9c52
                - name: haproxy
                  ref: dhi/haproxy:3.0.23-debian13@sha256:0c6831cc8dcefce628f14fb0edbd3e59f3c3ecb32f14f49000bb40dd35a00f2f
              name: vector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vectordotdev/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: vector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vector/config
