# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Collector Helm chart 0.x
image: dhi.io/opentelemetry-collector-chart
variant: helm
tags:
  - 0.156.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: a556bafceea1ebdbc4d250b652a2ff1dd2ff47c6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.152.1-debian13@sha256:74ea11fa5122d6f9e25d275a56ea4dc45f4159f030b726890939cbf7eb88dd90
  SEMVER_MAJOR_MINOR_VERSION: "0.156"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.156.1
  VERSION: 0.156.1
contents:
  builds:
    - name: opentelemetry-collector
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-collector-0.156.1
            checksum: a556bafceea1ebdbc4d250b652a2ff1dd2ff47c6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            chart:
              appRef: opentelemetry-collector
              description: Docker Hardened Images Helm chart for OpenTelemetry Collector
              images:
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.152.1-debian13@sha256:74ea11fa5122d6f9e25d275a56ea4dc45f4159f030b726890939cbf7eb88dd90
              name: opentelemetry-collector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-collector/config
