# syntax=dhi.io/build:2-helm3

name: ECK Operator Helm chart 3.x
image: dhi.io/eck-operator-chart
variant: helm
tags:
  - 3.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  ECK_OPERATOR_REFERENCE: dhi/eck-operator:3.4.0-debian13@sha256:0f4c9a0db178235335e48df8b004e68051e0d17b28db72db497d1256336a8484
  ELASTICSEARCH_REFERENCE: dhi/elasticsearch:9.4.1-debian13@sha256:bead201390ccd434ed2bba52467b481a61197eaa5b4dbf10c82e8479977cb270
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  KIBANA_REFERENCE: dhi/kibana:9.3.4-debian13@sha256:fe78bbde8bed2d77d985c010853e9cbe3605a6f47d00d6b9a15db295d3d58deb
  LOGSTASH_COMPAT_REFERENCE: dhi/logstash:9.3.4-debian13-compat@sha256:d15c9882d1fbde8fc56cc03681b9d05335a79257816adeaab28fc219624c3dfd
  SEMVER_MAJOR_MINOR_VERSION: "3.4"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.4.0
  VERSION: 3.4.0
contents:
  builds:
    - name: eck-operator
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/elastic/cloud-on-k8s.git#v3.4.0
            checksum: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            chart:
              appRef: eck-operator
              dependencies:
                - condition: installCRDs
                  keep: true
                  name: eck-operator-crds
              description: Docker Hardened Images Helm chart for Elastic Cloud on Kubernetes (ECK) Operator
              images:
                - name: eck-operator
                  ref: dhi/eck-operator:3.4.0-debian13@sha256:0f4c9a0db178235335e48df8b004e68051e0d17b28db72db497d1256336a8484
                - name: logstash
                  ref: dhi/logstash:9.3.4-debian13-compat@sha256:d15c9882d1fbde8fc56cc03681b9d05335a79257816adeaab28fc219624c3dfd
                - name: kibana
                  ref: dhi/kibana:9.3.4-debian13@sha256:fe78bbde8bed2d77d985c010853e9cbe3605a6f47d00d6b9a15db295d3d58deb
                - name: elasticsearch
                  ref: dhi/elasticsearch:9.4.1-debian13@sha256:bead201390ccd434ed2bba52467b481a61197eaa5b4dbf10c82e8479977cb270
              name: eck-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/elastic/cloud-on-k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy
          with:
            chart: eck-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/eck-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/eck-operator/config
