# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.20.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.20.2
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:16e923f8dd0ddc006a7bb1f2f389f0b034d5ef61133fa286792674a88aa83072
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:54cc7800db9fd750288fb512bc4a64e95f982c024db9bedb72291fb336c23cce
  CERT_MANAGER_COMMIT_SHA: e5b7b18450dd2c4b993b95bcd680b1a057205b00
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.20.2-debian13@sha256:d39cb1cab9c2ee4de5c35ac4146c3ac31b85b90239dd6963b77a218a68733659
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.20"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:b17220fde3c4c4745feb8325bde87d18b0b7f902015d8f66171ca533d73ba987
  CERT_MANAGER_VERSION: 1.20.2
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.20.2-debian13@sha256:53d78497144631384921903a886ca6c24242c25e6f85c0df3ef0dfe82869abf6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.20.2
            checksum: e5b7b18450dd2c4b993b95bcd680b1a057205b00
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.20.2-debian13@sha256:d39cb1cab9c2ee4de5c35ac4146c3ac31b85b90239dd6963b77a218a68733659
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:54cc7800db9fd750288fb512bc4a64e95f982c024db9bedb72291fb336c23cce
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:16e923f8dd0ddc006a7bb1f2f389f0b034d5ef61133fa286792674a88aa83072
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:b17220fde3c4c4745feb8325bde87d18b0b7f902015d8f66171ca533d73ba987
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.20.2-debian13@sha256:53d78497144631384921903a886ca6c24242c25e6f85c0df3ef0dfe82869abf6
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
