# syntax=dhi.io/build:2-helm3

name: Kured Helm chart 5.x
image: dhi.io/kured-chart
variant: helm
tags:
  - 5.11.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: cbd82b5ab365d91c65794febaa344d8db683948f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  KURED_IMAGE_REFERENCE: dhi/kured:1.21.0-debian13@sha256:0f487c2a3064400c27d11287e4f0a21a37db00b267e11fa47a14fa6d12f735c0
  SEMVER_MAJOR_MINOR_VERSION: "5.11"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.11.0
  VERSION: 5.11.0
contents:
  builds:
    - name: kured-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      work-dir: ${source.dir}/helm-charts/charts/kured
      contents:
        files:
          - url: git+https://github.com/kubereboot/charts.git#kured-5.11.0
            checksum: cbd82b5ab365d91c65794febaa344d8db683948f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kured
              description: Docker Hardened Images Helm chart for Kured
              images:
                - name: kured
                  ref: dhi/kured:1.21.0-debian13@sha256:0f487c2a3064400c27d11287e4f0a21a37db00b267e11fa47a14fa6d12f735c0
              name: kured-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubereboot/kured
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kured/config
