# syntax=dhi.io/build:2-helm3

name: Istio Discovery (istiod) Helm chart 1.x
image: dhi.io/istio-discovery-chart
variant: helm
tags:
  - 1.29.3
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4a7da1efa3f7e80fd69587831a3df7ccc2bd7622
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  ISTIO_PILOT_REFERENCE: dhi/istio-pilot:1.29.3-debian13@sha256:beef4643bf8b2d3ca0e901c32955e1d12066bbd84442d71c8e64b2cc71476afa
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.29.3-debian13@sha256:48add1488e9c961945eb9e874c6c22d1f1fd57449f50873a152b69e2182bfb5f
  SEMVER_MAJOR_MINOR_VERSION: "1.29"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.29.3
  VERSION: 1.29.3
contents:
  builds:
    - name: istio-discovery
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      work-dir: /src/go/github.com/istio/istio/manifests/charts/istio-control/istio-discovery
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.29.3
            checksum: 4a7da1efa3f7e80fd69587831a3df7ccc2bd7622
            path: /src/go/github.com/istio/istio
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: pilot
              description: Docker Hardened Images Helm chart for Istio Discovery (istiod)
              images:
                - name: pilot
                  ref: dhi/istio-pilot:1.29.3-debian13@sha256:beef4643bf8b2d3ca0e901c32955e1d12066bbd84442d71c8e64b2cc71476afa
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.29.3-debian13@sha256:48add1488e9c961945eb9e874c6c22d1f1fd57449f50873a152b69e2182bfb5f
              name: istio-discovery-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-discovery/config
