# syntax=dhi.io/build:2-helm3

name: Grafana Tempo Helm chart 2.x
image: dhi.io/tempo-chart
variant: helm
tags:
  - 2.1.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ccc92b999c5a33b485ae530a34d8c55dc9e021e2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  SEMVER_MAJOR_MINOR_VERSION: "2.1"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.1.2
  TEMPO_QUERY_REFERENCE: dhi/tempo-query:2.10.5-debian13@sha256:a3753d877eff2f4a4d5e4da5e8ceeaafdc7580be8f13f3c7965c1dd9d6bc1dd2
  TEMPO_REFERENCE: dhi/tempo:2.10.5-debian13@sha256:fe86c80563660ddab3a6482d5fef94198110659aa9c3a78b6251fecd194f581f
  VERSION: 2.1.2
contents:
  builds:
    - name: grafana-tempo
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      work-dir: ${source.dir}/helm-charts/charts/tempo
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#tempo-2.1.2
            checksum: ccc92b999c5a33b485ae530a34d8c55dc9e021e2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tempo
              description: Docker Hardened Images Helm chart for Grafana Tempo
              images:
                - name: tempo
                  ref: dhi/tempo:2.10.5-debian13@sha256:fe86c80563660ddab3a6482d5fef94198110659aa9c3a78b6251fecd194f581f
                - name: tempo-query
                  ref: dhi/tempo-query:2.10.5-debian13@sha256:a3753d877eff2f4a4d5e4da5e8ceeaafdc7580be8f13f3c7965c1dd9d6bc1dd2
              name: tempo-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-tempo/config
