operatorConfig:
  image:
    defaultRegistry: ${tailscale-operator.registry}
    repository: ${tailscale-operator.repository}
    tag: ${tailscale-operator.tag}@${tailscale-operator.digest}
proxyConfig:
  image:
    defaultRegistry: ${tailscale.registry}
    repository: ${tailscale.repository}
    tag: ${tailscale.tag}@${tailscale.digest}
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
