# syntax=dhi.io/build:2-debian13

name: Helm 4.x (dev)
image: dhi.io/helm
variant: dev
tags:
  - 4-dev
  - 4.2-dev
  - 4.2.0-dev
  - 4-debian13-dev
  - 4.2-debian13-dev
  - 4.2.0-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: 06468084e85c244c712834933d25ea232a4c2093
  GOLANG_REFERENCE: dhi/golang:1.26.3-debian13-dev@sha256:fd3180feff08929120077efe8799d54693a9861006cf400e5788591948f7402d
  SEMVER_MAJOR_MINOR_VERSION: "4.2"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.2.0
  VERSION: 4.2.0
  YQ_REFERENCE: dhi/pkg-go-yq:4.53.2-debian13@sha256:2298e6ae895fadd3dabc2ff821b9f56049cc004ba8005a79a28b4938e6a80d66
  YQ_VERSION: 4.53.2
contents:
  packages:
    - '!base-files'
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: helm
      uses: dhi.io/golang:1.26.3-debian13-dev@sha256:fd3180feff08929120077efe8799d54693a9861006cf400e5788591948f7402d
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v4.2.0
            checksum: 06468084e85c244c712834933d25ea232a4c2093
            path: /go/src/github.com/helm/helm
            spdx:
              name: helm
              version: 4.2.0
              packages:
                - name: helm
                  purl: pkg:golang/helm.sh/helm/v3@4.2.0
                  license: Apache-2.0
            uid: 65532
            gid: 65532
      pipeline:
        - name: update go dependencies
          uses: go/bump@v2
          with:
            deps:
              - golang.org/x/net@v0.53.0
            download: true
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.2.0
              - -X helm.sh/helm/v4/internal/version.gitCommit=06468084e85c244c712834933d25ea232a4c2093
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/local/bin/helm
            packages: ./cmd/helm
      accounts:
        run-as: nonroot
        users:
          - name: nonroot
            uid: 65532
            gid: 65532
        groups:
          - name: nonroot
            gid: 65532
            members:
              - nonroot
      outputs:
        - source: ${target.dir}/usr/local/bin
          target: /usr/local/bin
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/helm
          target: /opt/docker/sbom/helm
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-go-yq:4.53.2-debian13@sha256:2298e6ae895fadd3dabc2ff821b9f56049cc004ba8005a79a28b4938e6a80d66
      includes:
        - opt/docker/sbom/yq
        - usr/local/bin/yq
      uid: 0
      gid: 0
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /workspace
environment:
  DEBIAN_FRONTEND: noninteractive
paths:
  - type: directory
    path: /workspace
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Helm image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - helm
cmd:
  - help
