# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.3.3@sha256:89875ad1edc9cacff7e024335c66a941dfa46b4b940ea29bea34930d8d20eead
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.16.0@sha256:fa829be5762d38648864d318fafba3b25b8d8bf6a6f8a5fd37344b24402b63fb
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.29.6-cli-1.7.0-debian13@sha256:25a9b7192e853cf2aeeea4052352544156a1cbeb6585c6b5d348dfd6ab106f4e
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:8d2cb3855ff11ec204f33c07adf300e63fb26c45a200d108ee5a2c9fafc06f21
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.49.1-debian13@sha256:0589e66dd52d5ba9692d831b363ec9f7f4bac6949199ab82118ac9c0289c73a7
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.16.0@sha256:fa829be5762d38648864d318fafba3b25b8d8bf6a6f8a5fd37344b24402b63fb
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.3.3@sha256:89875ad1edc9cacff7e024335c66a941dfa46b4b940ea29bea34930d8d20eead
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:8d2cb3855ff11ec204f33c07adf300e63fb26c45a200d108ee5a2c9fafc06f21
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.29.6-cli-1.7.0-debian13@sha256:25a9b7192e853cf2aeeea4052352544156a1cbeb6585c6b5d348dfd6ab106f4e
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.49.1-debian13@sha256:0589e66dd52d5ba9692d831b363ec9f7f4bac6949199ab82118ac9c0289c73a7
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-0
