# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.3.3@sha256:d9ab0a4113848c40eeca85bbb70a17c79265eb6e4fe20481333910d416a2e096
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.16.0@sha256:c02ae94471987c79e55d60ea707d474b16aab7d8033a79bf39cf9e651b9ae4c0
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.29.6-cli-1.7.0-debian13@sha256:7b59054d03bfe7ff5b0791383d5ea869c4e34263bc076514aa082b87056897df
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:5f031c6a923f510aef28c350b5bba617afcd074bd6aaaf141fc831535e1345ce
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.49.1-debian13@sha256:acc43a495adc6da53e177c664fdfdddd6578f4a4d913eb8045ad005cdab67d53
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.16.0@sha256:c02ae94471987c79e55d60ea707d474b16aab7d8033a79bf39cf9e651b9ae4c0
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.3.3@sha256:d9ab0a4113848c40eeca85bbb70a17c79265eb6e4fe20481333910d416a2e096
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:5f031c6a923f510aef28c350b5bba617afcd074bd6aaaf141fc831535e1345ce
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.29.6-cli-1.7.0-debian13@sha256:7b59054d03bfe7ff5b0791383d5ea869c4e34263bc076514aa082b87056897df
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.49.1-debian13@sha256:acc43a495adc6da53e177c664fdfdddd6578f4a4d913eb8045ad005cdab67d53
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-0
