# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 1.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 1.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5721e9a3138dec93584ac231a8d57231234a6964
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  SEMVER_MAJOR_MINOR_VERSION: "1.2"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.2.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.31.0-cli-1.7.0-debian13@sha256:2f0ee209b960a4cb3ec2d20c0330aa40605a849ecd9ec594a4fcfbeed51c93de
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.31.0-debian13@sha256:dc7dbd8e48fefdbd9ec00ae86ccd25f155bd332460928bdf4c14a3e890734dba
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.49.1-debian13@sha256:0589e66dd52d5ba9692d831b363ec9f7f4bac6949199ab82118ac9c0289c73a7
  VERSION: 1.2.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-1.2.0
            checksum: 5721e9a3138dec93584ac231a8d57231234a6964
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.31.0-debian13@sha256:dc7dbd8e48fefdbd9ec00ae86ccd25f155bd332460928bdf4c14a3e890734dba
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.31.0-cli-1.7.0-debian13@sha256:2f0ee209b960a4cb3ec2d20c0330aa40605a849ecd9ec594a4fcfbeed51c93de
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.49.1-debian13@sha256:0589e66dd52d5ba9692d831b363ec9f7f4bac6949199ab82118ac9c0289c73a7
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . -f values/values.postgresql.yaml
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-1
