# syntax=dhi.io/build:2-helm3

name: Fairwinds VPA Helm chart 4.x
image: dhi.io/fairwinds-vpa-chart
variant: helm
tags:
  - 4.11.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 668395099685a5057ec86f0df71c028c46487243
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:843587c303e179531e1d803d5b022a551ac1122083d99bcde319c6d6d658bcbd
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:192c542342d8df9418e17303d59a976fa18b3b79b2b6680c1885c912b2ca5417
  METRICS_SERVER_REFERENCE: dhi/metrics-server-chart:3.13.0@sha256:a8c0a10253c4cfe5fd08ee03efe9a50db1c6179d45864270954f02f9a837bb12
  SEMVER_MAJOR_MINOR_VERSION: "4.11"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.11.0
  VERSION: 4.11.0
  VPA_ADMISSION_CONTROLLER_REFERENCE: dhi/vpa-admission-controller:1.6.0-debian13@sha256:96496269cbb3d7db6a120cdc3a0bbe72d2f677fa749617464da8d9d02b8f49d9
  VPA_RECOMMENDER_REFERENCE: dhi/vpa-recommender:1.6.0-debian13@sha256:4a774ecc8ca369bd07e29033f83217ef21c2afa9a8a2ac683c058f2e1db8e535
  VPA_UPDATER_REFERENCE: dhi/vpa-updater:1.6.0-debian13@sha256:9147b6ebb7d77c3b2a5d98f842c2227a0bfe726f50012d35f36d414d7507c4d1
contents:
  builds:
    - name: fairwinds-vpa-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:f4a916b146b07955a0f7f705854bfda3af7853e4cedb839335d4d269004cbf00
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#668395099685a5057ec86f0df71c028c46487243
            checksum: 668395099685a5057ec86f0df71c028c46487243
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            chart:
              appRef: vpa-admission-controller
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.0@sha256:a8c0a10253c4cfe5fd08ee03efe9a50db1c6179d45864270954f02f9a837bb12
              description: Docker Hardened Images Helm chart for Fairwinds VPA
              images:
                - name: vpa-admission-controller
                  ref: dhi/vpa-admission-controller:1.6.0-debian13@sha256:96496269cbb3d7db6a120cdc3a0bbe72d2f677fa749617464da8d9d02b8f49d9
                - name: vpa-recommender
                  ref: dhi/vpa-recommender:1.6.0-debian13@sha256:4a774ecc8ca369bd07e29033f83217ef21c2afa9a8a2ac683c058f2e1db8e535
                - name: vpa-updater
                  ref: dhi/vpa-updater:1.6.0-debian13@sha256:9147b6ebb7d77c3b2a5d98f842c2227a0bfe726f50012d35f36d414d7507c4d1
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:843587c303e179531e1d803d5b022a551ac1122083d99bcde319c6d6d658bcbd
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:192c542342d8df9418e17303d59a976fa18b3b79b2b6680c1885c912b2ca5417
              name: fairwinds-vpa-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: vpa
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fairwinds-vpa/config
